// Generates film/data/earth.js from Natural Earth land polygons
// (world-atlas@2 land-110m.json, public domain) so the film has no runtime
// network dependency.
//
//   npm pack world-atlas topojson-client   # then extract both
//   node tools/build-earth.mjs <land-110m.json> <topojson-client dir>

import fs from 'node:fs';
import path from 'node:path';
import { createRequire } from 'node:module';

const [landPath, topoDir] = process.argv.slice(2);
if (!landPath || !topoDir) {
  console.error('usage: node tools/build-earth.mjs <land-110m.json> <topojson-client dir>');
  process.exit(1);
}
const require = createRequire(import.meta.url);
const topojson = require(path.resolve(topoDir, 'dist/topojson-client.js'));
const topo = JSON.parse(fs.readFileSync(landPath, 'utf8'));
const land = topojson.feature(topo, topo.objects.land);

const polys = [];
for (const f of land.features) {
  const g = f.geometry;
  const list = g.type === 'Polygon' ? [g.coordinates] : g.coordinates;
  for (const p of list) polys.push(p);
}

function inRing(x, y, ring) {
  let inside = false;
  for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
    const [xi, yi] = ring[i], [xj, yj] = ring[j];
    if ((yi > y) !== (yj > y) && x < ((xj - xi) * (y - yi)) / (yj - yi) + xi) inside = !inside;
  }
  return inside;
}
function isLand(lon, lat) {
  for (const p of polys) {
    if (inRing(lon, lat, p[0])) {
      let hole = false;
      for (let k = 1; k < p.length; k++) if (inRing(lon, lat, p[k])) hole = true;
      if (!hole) return true;
    }
  }
  return false;
}

// Roughly equal-area stipple grid.
const STEP = 1.1;
const dots = [];
for (let lat = -84; lat <= 84; lat += STEP) {
  const lonStep = STEP / Math.max(0.15, Math.cos((lat * Math.PI) / 180));
  for (let lon = -180; lon < 180; lon += lonStep) {
    if (isLand(lon, lat)) dots.push(Math.round(lat * 10), Math.round(lon * 10));
  }
}

// Coastlines, lightly decimated.
const coasts = [];
for (const p of polys) {
  const ring = p[0];
  if (ring.length < 8) continue;
  const out = [];
  for (let i = 0; i < ring.length; i += 2) out.push(Math.round(ring[i][1] * 10), Math.round(ring[i][0] * 10));
  coasts.push(out);
}

const js =
  '// Generated by tools/build-earth.mjs from Natural Earth (public domain). Values are degrees x10.\n' +
  `window.EARTH = {dots:${JSON.stringify(dots)},coasts:${JSON.stringify(coasts)}};\n`;
fs.writeFileSync(new URL('../film/data/earth.js', import.meta.url), js);
console.log(`dots: ${dots.length / 2}, coast rings: ${coasts.length}, bytes: ${js.length}`);
